blank_issues_enabled: true
contact_links:
  - name: Get support on Discord
    url: https://discord.com/channels/1003691521280856084/1003691521721245792
    about: Reach out on Discord in the floating-ui-svelte channel
  - name: Ask a question, give feedback, share your project
    url: https://github.com/skeletonlabs/floating-ui-svelte/discussions
    about: Connect with other community members with GitHub discussions
